### ISSUE TITLE
Your first MAST-ML run: " ValueError: 'X' and 'missing_values' types are expected to be both numerical. Got X.dtype=float64 and  type(missing_values)=<class 'str'>. "

### ISSUE THREAD

**Issue by Andrewwwwwong** [uw-cmg/MAST-ML#216] opened 2020-06-24 07:59 UTC
I am trying to complete the guided run for MAST-ML on Jupyter notebook. My input is

from mastml import mastml_driver
conf_path = 'C:/Users/Public/Anaconda/Lib/site-packages/mastml/tests/conf/example_input.conf'
data_path = 'C:/Users/Public/Anaconda/Lib/site-packages/mastml/tests/csv/example_data.csv'
results_path = 'C:/Users/Public/Anaconda/Lib/site-packages/mastml/tests/results/mastml_tutorial'
mastml_driver.main(conf_path, data_path, results_path)

with the conf and data files being the ones provided from the website. However, I run into this error, any advice on how to work around it? 

[GeneralSetup]
    input_features = Auto
    input_target = Reduced barrier (eV)
    randomizer = False
    metrics = Auto
    input_other = Host element, Solute element, predict_Pt
    input_grouping = Host element
    input_testdata = predict_Pt

[DataCleaning]
    cleaning_method = imputation
    imputation_strategy = mean

[FeatureNormalization]
    [[StandardScaler]]
    #[[MeanStdevScaler]]
    #    mean = 1
    #    stdev = 5

[FeatureGeneration]
    [[Magpie]]
        composition_feature = Solute element
        feature_types = composition_avg, arithmetic_avg, max, min, difference, elements

#[FeatureSelection]
#    [[MASTMLFeatureSelector]]
#        n_features_to_select = 3
#        cv = LeaveOneGroupOut_select
#        estimator = KernelRidge_select

[DataSplits]
    #[[NoSplit]]
    [[RepeatedKFold]]
        n_splits = 3
        n_repeats = 2
    #[[LeaveOneGroupOut_select]]
    #    grouping_column = Host element

[Models]
	#[[GaussianProcessRegressor]]
	#[[RandomForestRegressor]]
	[[KernelRidge]]
     	alpha = 0.009
		gamma = 0.027
		kernel = rbf
	#[[KernelRidge_select]]
    # 	alpha = 0.009
	#	gamma = 0.027
	#	kernel = rbf

[MiscSettings]
    plot_target_histogram = True
    plot_train_test_plots = True
    plot_predicted_vs_true = True
    plot_predicted_vs_true_average = True
    plot_best_worst_per_point = True
    plot_each_feature_vs_target = False
    plot_error_plots = True
    rf_error_method = stdev
    rf_error_percentile = 95
    normalize_target_feature = False

**Comment by rjacobs914** [comment] 2020-06-24 14:10
I was able to run the provided example.conf without issue. Here, it looks as though the FeatureSelection block has been changed, where the line "FeatureSelection" is commented out but the lines below it are not. Could you try fully commenting out the FeatureSelection section and re-running?

**Comment by Andrewwwwwong** [comment] 2020-06-25 00:46
It still results in an error. This is the full error message

ValueError                                Traceback (most recent call last)
<ipython-input-1-61402ab3f8b6> in <module>
      3 data_path = 'C:/Users/Public/Anaconda/Lib/site-packages/mastml/tests/csv/example_data.csv'
      4 results_path = 'C:/Users/Public/Anaconda/Lib/site-packages/mastml/tests/results/mastml_tutorial'
----> 5 mastml_driver.main(conf_path, data_path, results_path)

C:\Users\Public\Anaconda\lib\site-packages\mastml\mastml_driver.py in main(conf_path, data_path, outdir, verbosity)
     72                       'https://github.com/uw-cmg/MAST-ML/issues and post your issue.')
     73         log.exception(e)
---> 74         raise e
     75     return outdir # so a calling program can know where we actually saved it
     76 

C:\Users\Public\Anaconda\lib\site-packages\mastml\mastml_driver.py in main(conf_path, data_path, outdir, verbosity)
     63 
     64     try:
---> 65         mastml_run(conf_path, data_path, outdir)
     66     except utils.MastError as e:
     67         # catch user errors, log and print, but don't raise and show them that nasty stack

C:\Users\Public\Anaconda\lib\site-packages\mastml\mastml_driver.py in mastml_run(conf_path, data_path, outdir)
    159                             "the mean will be used as the imputation strategy")
    160                 dc['imputation_strategy'] = 'mean'
--> 161             df = data_cleaner.imputation(df, dc['imputation_strategy'], X_noinput.columns)
    162             X = data_cleaner.imputation(X, dc['imputation_strategy'])
    163         elif dc['cleaning_method'] == 'ppca':

C:\Users\Public\Anaconda\lib\site-packages\mastml\data_cleaner.py in imputation(df, strategy, cols_to_leave_out)
     83         df_include = df.drop(cols_to_leave_out, axis=1)
     84         df_hold_out = df.drop([c for c in df.columns if c not in cols_to_leave_out], axis=1)
---> 85         df_imputed = pd.DataFrame(SimpleImputer(missing_values='NaN', strategy=strategy).fit_transform(df_include), columns=df_include.columns)
     86     # Need to join the imputed dataframe with the columns containing strings that were held out
     87     if cols_to_leave_out is None:

C:\Users\Public\Anaconda\lib\site-packages\sklearn\base.py in fit_transform(self, X, y, **fit_params)
    688         if y is None:
    689             # fit method of arity 1 (unsupervised transformation)
--> 690             return self.fit(X, **fit_params).transform(X)
    691         else:
    692             # fit method of arity 2 (supervised transformation)

C:\Users\Public\Anaconda\lib\site-packages\sklearn\impute\_base.py in fit(self, X, y)
    275         self : SimpleImputer
    276         """
--> 277         X = self._validate_input(X, in_fit=True)
    278         super()._fit_indicator(X)
    279 

C:\Users\Public\Anaconda\lib\site-packages\sklearn\impute\_base.py in _validate_input(self, X, in_fit)
    251                 raise ve
    252 
--> 253         _check_inputs_dtype(X, self.missing_values)
    254         if X.dtype.kind not in ("i", "u", "f", "O"):
    255             raise ValueError("SimpleImputer does not support data with dtype "

C:\Users\Public\Anaconda\lib\site-packages\sklearn\impute\_base.py in _check_inputs_dtype(X, missing_values)
     26                          " both numerical. Got X.dtype={} and "
     27                          " type(missing_values)={}."
---> 28                          .format(X.dtype, type(missing_values)))
     29 
     30 

ValueError: 'X' and 'missing_values' types are expected to be both numerical. Got X.dtype=float64 and  type(missing_values)=<class 'str'>.

**Comment by Andrewwwwwong** [comment] 2020-06-25 00:47
> I was able to run the provided example.conf without issue. Here, it looks as though the FeatureSelection block has been changed, where the line "FeatureSelection" is commented out but the lines below it are not. Could you try fully commenting out the FeatureSelection section and re-running?

It still results in the same error. Here is the full error message:

ValueError                                Traceback (most recent call last)
<ipython-input-1-61402ab3f8b6> in <module>
      3 data_path = 'C:/Users/Public/Anaconda/Lib/site-packages/mastml/tests/csv/example_data.csv'
      4 results_path = 'C:/Users/Public/Anaconda/Lib/site-packages/mastml/tests/results/mastml_tutorial'
----> 5 mastml_driver.main(conf_path, data_path, results_path)

C:\Users\Public\Anaconda\lib\site-packages\mastml\mastml_driver.py in main(conf_path, data_path, outdir, verbosity)
     72                       'https://github.com/uw-cmg/MAST-ML/issues and post your issue.')
     73         log.exception(e)
---> 74         raise e
     75     return outdir # so a calling program can know where we actually saved it
     76 

C:\Users\Public\Anaconda\lib\site-packages\mastml\mastml_driver.py in main(conf_path, data_path, outdir, verbosity)
     63 
     64     try:
---> 65         mastml_run(conf_path, data_path, outdir)
     66     except utils.MastError as e:
     67         # catch user errors, log and print, but don't raise and show them that nasty stack

C:\Users\Public\Anaconda\lib\site-packages\mastml\mastml_driver.py in mastml_run(conf_path, data_path, outdir)
    159                             "the mean will be used as the imputation strategy")
    160                 dc['imputation_strategy'] = 'mean'
--> 161             df = data_cleaner.imputation(df, dc['imputation_strategy'], X_noinput.columns)
    162             X = data_cleaner.imputation(X, dc['imputation_strategy'])
    163         elif dc['cleaning_method'] == 'ppca':

C:\Users\Public\Anaconda\lib\site-packages\mastml\data_cleaner.py in imputation(df, strategy, cols_to_leave_out)
     83         df_include = df.drop(cols_to_leave_out, axis=1)
     84         df_hold_out = df.drop([c for c in df.columns if c not in cols_to_leave_out], axis=1)
---> 85         df_imputed = pd.DataFrame(SimpleImputer(missing_values='NaN', strategy=strategy).fit_transform(df_include), columns=df_include.columns)
     86     # Need to join the imputed dataframe with the columns containing strings that were held out
     87     if cols_to_leave_out is None:

C:\Users\Public\Anaconda\lib\site-packages\sklearn\base.py in fit_transform(self, X, y, **fit_params)
    688         if y is None:
    689             # fit method of arity 1 (unsupervised transformation)
--> 690             return self.fit(X, **fit_params).transform(X)
    691         else:
    692             # fit method of arity 2 (supervised transformation)

C:\Users\Public\Anaconda\lib\site-packages\sklearn\impute\_base.py in fit(self, X, y)
    275         self : SimpleImputer
    276         """
--> 277         X = self._validate_input(X, in_fit=True)
    278         super()._fit_indicator(X)
    279 

C:\Users\Public\Anaconda\lib\site-packages\sklearn\impute\_base.py in _validate_input(self, X, in_fit)
    251                 raise ve
    252 
--> 253         _check_inputs_dtype(X, self.missing_values)
    254         if X.dtype.kind not in ("i", "u", "f", "O"):
    255             raise ValueError("SimpleImputer does not support data with dtype "

C:\Users\Public\Anaconda\lib\site-packages\sklearn\impute\_base.py in _check_inputs_dtype(X, missing_values)
     26                          " both numerical. Got X.dtype={} and "
     27                          " type(missing_values)={}."
---> 28                          .format(X.dtype, type(missing_values)))
     29 
     30 

ValueError: 'X' and 'missing_values' types are expected to be both numerical. Got X.dtype=float64 and  type(missing_values)=<class 'str'>.

**Comment by rjacobs914** [comment] 2020-06-25 13:52
Do you have any X features (i.e any columns in data file that are not the target) which are strings and not included in the input_other category? If so, I think this error will result. The issue is MAST-ML is attempting to do some computations on columns which are containing strings, and would result in such an error. In general, all "extra" columns not directly used in fitting a model will need to be listed in the input_other field

**Comment by rjacobs914** [comment] 2020-06-25 13:53
One other thing to try is to save the data file in .xlsx format instead of .csv. Sometimes the plain text csv can add some hidden characters that can result in errors like this

**Comment by Andrewwwwwong** [comment] 2020-06-26 01:01
> Do you have any X features (i.e any columns in data file that are not the target) which are strings and not included in the input_other category? If so, I think this error will result. The issue is MAST-ML is attempting to do some computations on columns which are containing strings, and would result in such an error. In general, all "extra" columns not directly used in fitting a model will need to be listed in the input_other field

I do not believe so, I did not change anything after downloading the file off from the MAST-ML site

**Comment by Andrewwwwwong** [comment] 2020-06-26 01:05
> One other thing to try is to save the data file in .xlsx format instead of .csv. Sometimes the plain text csv can add some hidden characters that can result in errors like this

This obtains the same error with an identical error path

**Comment by rjacobs914** [comment] 2021-07-08 16:24
No longer relevant for current mastml version- closing

**Closed by rjacobs914** 2021-07-08 16:24 UTC
