### ISSUE TITLE
MAST-ML Installation

### ISSUE THREAD

**Issue by ghost** [uw-cmg/MAST-ML#214] opened 2020-01-17 19:31 UTC
Hello,

I'm having trouble setting up MAST-ML on my laptop, (macOS Catalina 10.15.2).

I've followed the instructions and seems that all the preliminary packages were successfully installed (no errors when installing numpy, scitkit, patmagen...) until the "python setup.py install step". That's where I get an error. I attached the terminal output.

I appreciate your help with this issue.

- Omar B.
[python_setuppy_install.txt](https://github.com/uw-cmg/MAST-ML/files/4078636/python_setuppy_install.txt)

**Comment by rjacobs914** [comment] 2020-01-17 19:39
Did you git clone the repo or do a pip install of mastml?

If you did not do a pip install, could you try that and see if the issue is resolved (pip install mastml)

**Comment by rjacobs914** [comment] 2021-07-08 16:24
No longer relevant for current mastml version- closing

**Closed by rjacobs914** 2021-07-08 16:24 UTC
